### ISSUE TITLE
사진 파일 이외의 다른 파일을 첨부할 수 있습니다.

### ISSUE THREAD

**Issue by happy-spark** [Advent-calendar-by-likeLion/AdventCalendar#70]
안녕하세요. 편지를 보낼 때 이미지 업로드 버튼을 누르고 파일을 첨부할 때 파일 형식을 다음과 같이 변경하면, 사진 이외의 다른 파일도 첨부할 수 있게 됩니다.

![image](https://user-images.githubusercontent.com/107300540/205302115-94c72cfc-09f8-44d8-af1e-89f7c2022fe2.png)

이와 같은 방법으로 첨부된 파일은 받는 사람인 호텔의 주인이 일반적인 방법으로는 확인하지 못 하지만, 웹에서 개발자 도구를 사용하면 firebase에 저장된 파일 링크가 보여서 결국에는, 사진 이외의 파일을 첨부하고 확인할 수 있는 겁니다. 다시 한번 검토 부탁드립니다. 감사합니다.

**Comment by khsrla9806** [comment]
해당 문제 검토해보겠습니다! 감사합니다!
