### ISSUE TITLE
env/API key 공개

### ISSUE THREAD

**Issue by hwuiwon** [Advent-calendar-by-likeLion/AdventCalendar#77]
아랫분이 말씀하신 것처럼 레포 비공개하고 API 키 새로 재발급 받는 것 추천드려요.

이러다가 잘못하면 수백만원 단위로 사용 요금 charge 당할 수 있습니다.

- https://github.com/Advent-calendar-by-likeLion/AdventCalendar/blob/main/src/fbase.js
- https://github.com/Advent-calendar-by-likeLion/AdventCalendar/blob/main/.env

**Comment by hwuiwon** [comment]
@khsrla9806

**Comment by khsrla9806** [comment]
답변 감사합니다! 확인해보도록 하겠습니다.
